export const ADD_INGREDIENT="ADD_INGREDIENT"
export const REMOVE_INGREDIENT="REMOVE_INGREDIENT"
export const SET_INGREDIENT="SET_INGREDIENT"
export const ERROR_ONINGREDIENTS="ERROR_ONINGREDIENTS"
export const PERFORM_ORDER_SUCCESS="PERFORM_ORDER_SUCCESS"
export const ERROR_ON_SUBMIT="ERROR_ON_SUBMIT"
export const PERFORM_ORDER_SUBMIT_LOADING="PERFORM_ORDER_SUBMIT_LOADING"
export const REDIRECT_AFTER_PURCHASE="REDIRECT_AFTER_PURCHASE"

export const ORDER_FETCH_FROM_API="ORDER_FETCH_FROM_API"
export const ORDER_SUCCESS="ORDER_SUCCESS"
export const ORDER_FAILURE="ORDER_FAILURE"
export const ORDER_FETCH_START="ORDER_FETCH_START"


export const AUTH_START="AUTH_START"
export const AUTH_SUCCESS="AUTH_SUCCESS"
export const AUTH_FAIL="AUTH_FAIL"

export const AUTH_LOGOUT="AUTH_LOGOUT"

export const SET_AUTH_REDIRECT="SET_AUTH_REDIRECT"